name: Build Forge Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Make Gradle executable
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --max-workers=2 -Dorg.gradle.jvmargs="-Xmx3G"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutoAim-Mod
          path: build/libs/*.jar
